/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGAStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        MKS_MicrovisionIP_RGAStateMachine.cpp
//
// description : State machine file for the MKS_MicrovisionIP_RGA class
//
// project :     MKS Microvision IP RGA
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <MKS_MicrovisionIP_RGA.h>

/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::MKS_MicrovisionIP_RGAStateMachine.cpp

//================================================================
//  States   |  Description
//================================================================
//  ON       |  The RGA is scanning.
//  FAULT    |  The RGA is not scanning.
//  DISABLE  |  The RGA is currently in Use by another application.
//  INIT     |  The Unit is ready for use but is not yet scanning.


namespace MKS_MicrovisionIP_RGA_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : MKS_MicrovisionIP_RGA::is_MeasurementMode_allowed()
 *	Description : Execution allowed for MeasurementMode attribute
 */
//--------------------------------------------------------
bool MKS_MicrovisionIP_RGA::is_MeasurementMode_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for MeasurementMode attribute in Write access.
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::MeasurementModeStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::MeasurementModeStateAllowed_WRITE

	//	Not any excluded states for MeasurementMode attribute in read access.
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::MeasurementModeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::MeasurementModeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MKS_MicrovisionIP_RGA::is_Accuracy_allowed()
 *	Description : Execution allowed for Accuracy attribute
 */
//--------------------------------------------------------
bool MKS_MicrovisionIP_RGA::is_Accuracy_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Accuracy attribute in Write access.
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::AccuracyStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::AccuracyStateAllowed_WRITE

	//	Not any excluded states for Accuracy attribute in read access.
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::AccuracyStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::AccuracyStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MKS_MicrovisionIP_RGA::is_FilamentNumber_allowed()
 *	Description : Execution allowed for FilamentNumber attribute
 */
//--------------------------------------------------------
bool MKS_MicrovisionIP_RGA::is_FilamentNumber_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for FilamentNumber attribute in Write access.
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::FilamentNumberStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::FilamentNumberStateAllowed_WRITE

	//	Not any excluded states for FilamentNumber attribute in read access.
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::FilamentNumberStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::FilamentNumberStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MKS_MicrovisionIP_RGA::is_DetectorIndex_allowed()
 *	Description : Execution allowed for DetectorIndex attribute
 */
//--------------------------------------------------------
bool MKS_MicrovisionIP_RGA::is_DetectorIndex_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for DetectorIndex attribute in Write access.
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::DetectorIndexStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::DetectorIndexStateAllowed_WRITE

	//	Not any excluded states for DetectorIndex attribute in read access.
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::DetectorIndexStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::DetectorIndexStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MKS_MicrovisionIP_RGA::is_DetectorVoltage_allowed()
 *	Description : Execution allowed for DetectorVoltage attribute
 */
//--------------------------------------------------------
bool MKS_MicrovisionIP_RGA::is_DetectorVoltage_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for DetectorVoltage attribute in Write access.
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::DetectorVoltageStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::DetectorVoltageStateAllowed_WRITE

	//	Not any excluded states for DetectorVoltage attribute in read access.
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::DetectorVoltageStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::DetectorVoltageStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MKS_MicrovisionIP_RGA::is_StartMass_allowed()
 *	Description : Execution allowed for StartMass attribute
 */
//--------------------------------------------------------
bool MKS_MicrovisionIP_RGA::is_StartMass_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for StartMass attribute in Write access.
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::StartMassStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::StartMassStateAllowed_WRITE

	//	Not any excluded states for StartMass attribute in read access.
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::StartMassStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::StartMassStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MKS_MicrovisionIP_RGA::is_EndMass_allowed()
 *	Description : Execution allowed for EndMass attribute
 */
//--------------------------------------------------------
bool MKS_MicrovisionIP_RGA::is_EndMass_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for EndMass attribute in Write access.
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::EndMassStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::EndMassStateAllowed_WRITE

	//	Not any excluded states for EndMass attribute in read access.
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::EndMassStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::EndMassStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MKS_MicrovisionIP_RGA::is_LeakCheckMass_allowed()
 *	Description : Execution allowed for LeakCheckMass attribute
 */
//--------------------------------------------------------
bool MKS_MicrovisionIP_RGA::is_LeakCheckMass_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for LeakCheckMass attribute in Write access.
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::LeakCheckMassStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::LeakCheckMassStateAllowed_WRITE

	//	Not any excluded states for LeakCheckMass attribute in read access.
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::LeakCheckMassStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::LeakCheckMassStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MKS_MicrovisionIP_RGA::is_Timeout_allowed()
 *	Description : Execution allowed for Timeout attribute
 */
//--------------------------------------------------------
bool MKS_MicrovisionIP_RGA::is_Timeout_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Timeout attribute in Write access.
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::TimeoutStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::TimeoutStateAllowed_WRITE

	//	Not any excluded states for Timeout attribute in read access.
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::TimeoutStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::TimeoutStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MKS_MicrovisionIP_RGA::is_Gain_allowed()
 *	Description : Execution allowed for Gain attribute
 */
//--------------------------------------------------------
bool MKS_MicrovisionIP_RGA::is_Gain_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Gain attribute in Write access.
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::GainStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::GainStateAllowed_WRITE

	//	Not any excluded states for Gain attribute in read access.
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::GainStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::GainStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MKS_MicrovisionIP_RGA::is_SourceIndex_allowed()
 *	Description : Execution allowed for SourceIndex attribute
 */
//--------------------------------------------------------
bool MKS_MicrovisionIP_RGA::is_SourceIndex_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for SourceIndex attribute in Write access.
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::SourceIndexStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::SourceIndexStateAllowed_WRITE

	//	Not any excluded states for SourceIndex attribute in read access.
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::SourceIndexStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::SourceIndexStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MKS_MicrovisionIP_RGA::is_FilterMode_allowed()
 *	Description : Execution allowed for FilterMode attribute
 */
//--------------------------------------------------------
bool MKS_MicrovisionIP_RGA::is_FilterMode_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for FilterMode attribute in Write access.
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::FilterModeStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::FilterModeStateAllowed_WRITE

	//	Not any excluded states for FilterMode attribute in read access.
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::FilterModeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::FilterModeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MKS_MicrovisionIP_RGA::is_LeakCheckPressure_allowed()
 *	Description : Execution allowed for LeakCheckPressure attribute
 */
//--------------------------------------------------------
bool MKS_MicrovisionIP_RGA::is_LeakCheckPressure_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for LeakCheckPressure attribute in read access.
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::LeakCheckPressureStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::LeakCheckPressureStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MKS_MicrovisionIP_RGA::is_DegasStatus_allowed()
 *	Description : Execution allowed for DegasStatus attribute
 */
//--------------------------------------------------------
bool MKS_MicrovisionIP_RGA::is_DegasStatus_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for DegasStatus attribute in read access.
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::DegasStatusStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::DegasStatusStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MKS_MicrovisionIP_RGA::is_FilamentDegas_allowed()
 *	Description : Execution allowed for FilamentDegas attribute
 */
//--------------------------------------------------------
bool MKS_MicrovisionIP_RGA::is_FilamentDegas_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for FilamentDegas attribute in Write access.
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::FilamentDegasStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::FilamentDegasStateAllowed_WRITE

	//	Not any excluded states for FilamentDegas attribute in read access.
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::FilamentDegasStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::FilamentDegasStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MKS_MicrovisionIP_RGA::is_LifetimePressure_allowed()
 *	Description : Execution allowed for LifetimePressure attribute
 */
//--------------------------------------------------------
bool MKS_MicrovisionIP_RGA::is_LifetimePressure_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for LifetimePressure attribute in read access.
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::LifetimePressureStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::LifetimePressureStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MKS_MicrovisionIP_RGA::is_Masses_allowed()
 *	Description : Execution allowed for Masses attribute
 */
//--------------------------------------------------------
bool MKS_MicrovisionIP_RGA::is_Masses_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for Masses attribute in read access.
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::MassesStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::MassesStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MKS_MicrovisionIP_RGA::is_MassesHistory_allowed()
 *	Description : Execution allowed for MassesHistory attribute
 */
//--------------------------------------------------------
bool MKS_MicrovisionIP_RGA::is_MassesHistory_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for MassesHistory attribute in read access.
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::MassesHistoryStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::MassesHistoryStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MKS_MicrovisionIP_RGA::is_StaticPressures_allowed()
 *	Description : Execution allowed for StaticPressures attribute
 */
//--------------------------------------------------------
bool MKS_MicrovisionIP_RGA::is_StaticPressures_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for StaticPressures attribute in read access.
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::StaticPressuresStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::StaticPressuresStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MKS_MicrovisionIP_RGA::is_MassScalarAttrib_allowed()
 *	Description : Execution allowed for MassScalarAttrib attribute
 */
//--------------------------------------------------------
bool MKS_MicrovisionIP_RGA::is_MassScalarAttrib_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for MassScalarAttrib attribute in read access.
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::MassScalarAttribStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::MassScalarAttribStateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : MKS_MicrovisionIP_RGA::is_On_allowed()
 *	Description : Execution allowed for On attribute
 */
//--------------------------------------------------------
bool MKS_MicrovisionIP_RGA::is_On_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for On command.
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::OnStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::OnStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MKS_MicrovisionIP_RGA::is_Off_allowed()
 *	Description : Execution allowed for Off attribute
 */
//--------------------------------------------------------
bool MKS_MicrovisionIP_RGA::is_Off_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Off command.
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::OffStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::OffStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MKS_MicrovisionIP_RGA::is_Reset_allowed()
 *	Description : Execution allowed for Reset attribute
 */
//--------------------------------------------------------
bool MKS_MicrovisionIP_RGA::is_Reset_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Reset command.
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::ResetStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::ResetStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MKS_MicrovisionIP_RGA::is_SendCmd_allowed()
 *	Description : Execution allowed for SendCmd attribute
 */
//--------------------------------------------------------
bool MKS_MicrovisionIP_RGA::is_SendCmd_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for SendCmd command.
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::SendCmdStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::SendCmdStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MKS_MicrovisionIP_RGA::is_Release_allowed()
 *	Description : Execution allowed for Release attribute
 */
//--------------------------------------------------------
bool MKS_MicrovisionIP_RGA::is_Release_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Release command.
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::ReleaseStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::ReleaseStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MKS_MicrovisionIP_RGA::is_StartDegas_allowed()
 *	Description : Execution allowed for StartDegas attribute
 */
//--------------------------------------------------------
bool MKS_MicrovisionIP_RGA::is_StartDegas_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for StartDegas command.
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::StartDegasStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::StartDegasStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MKS_MicrovisionIP_RGA::is_StopDegas_allowed()
 *	Description : Execution allowed for StopDegas attribute
 */
//--------------------------------------------------------
bool MKS_MicrovisionIP_RGA::is_StopDegas_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for StopDegas command.
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::StopDegasStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::StopDegasStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MKS_MicrovisionIP_RGA::is_StoreStaticPress_allowed()
 *	Description : Execution allowed for StoreStaticPress attribute
 */
//--------------------------------------------------------
bool MKS_MicrovisionIP_RGA::is_StoreStaticPress_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for StoreStaticPress command.
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::StoreStaticPressStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::StoreStaticPressStateAllowed
	return true;
}


/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::MKS_MicrovisionIP_RGAStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::MKS_MicrovisionIP_RGAStateAllowed.AdditionalMethods

}	//	End of namespace
