/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::DynAttrUtils.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        MKS_MicrovisionIP_RGADynAttrUtils.cpp
//
// description : Dynamic attributes utilities file for the MKS_MicrovisionIP_RGA class
//
// project :     MKS Microvision IP RGA
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <MKS_MicrovisionIP_RGA.h>
#include <MKS_MicrovisionIP_RGAClass.h>

/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::DynAttrUtils.cpp

//================================================================
//  Attributes managed is:
//================================================================
//  MassScalarAttrib  |  Tango::DevDouble	Scalar
//================================================================

//	For compatibility reason, this file (MKS_MicrovisionIP_RGADynAttrUtils)
//	manage also the dynamic command utilities.
//================================================================
//  The following table gives the correspondence
//  between command and method names.
//
//  Command name  |  Method name
//================================================================
//================================================================

namespace MKS_MicrovisionIP_RGA_ns
{
//=============================================================
//	Add/Remove dynamic attribute methods
//=============================================================

//--------------------------------------------------------
/**
 *	Add a MassScalarAttrib dynamic attribute.
 *
 *  parameter attname: attribute name to be cretated and added.
 */
//--------------------------------------------------------
void MKS_MicrovisionIP_RGA::add_MassScalarAttrib_dynamic_attribute(string attname)
{
	//	Attribute : MassScalarAttrib
	MassScalarAttribAttrib	*massscalarattrib = new MassScalarAttribAttrib(attname);
	Tango::UserDefaultAttrProp	massscalarattrib_prop;
	//	description	not set for MassScalarAttrib
	//	label	not set for MassScalarAttrib
	massscalarattrib_prop.set_unit("mBar");
	//	standard_unit	not set for MassScalarAttrib
	//	display_unit	not set for MassScalarAttrib
	massscalarattrib_prop.set_format("%.3e");
	//	max_value	not set for MassScalarAttrib
	//	min_value	not set for MassScalarAttrib
	//	max_alarm	not set for MassScalarAttrib
	//	min_alarm	not set for MassScalarAttrib
	//	max_warning	not set for MassScalarAttrib
	//	min_warning	not set for MassScalarAttrib
	//	delta_t	not set for MassScalarAttrib
	//	delta_val	not set for MassScalarAttrib
	
	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::att_MassScalarAttrib_dynamic_attribute) ENABLED START -----*/
	
	massscalarattrib_prop.set_label(attname.c_str());
	
	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::att_MassScalarAttrib_dynamic_attribute
	massscalarattrib->set_default_properties(massscalarattrib_prop);
	//	Not Polled
	massscalarattrib->set_disp_level(Tango::EXPERT);
	//	Not Memorized
	massscalarattrib->set_change_event(true, false);
	massscalarattrib->set_archive_event(true, true);
	MassScalarAttrib_data.insert(make_pair(attname, 0.0));
	add_attribute(massscalarattrib);
}
//--------------------------------------------------------
/**
 *	remove a MassScalarAttrib dynamic attribute.
 *
 *  parameter attname: attribute name to be removed.
 */
//--------------------------------------------------------
void MKS_MicrovisionIP_RGA::remove_MassScalarAttrib_dynamic_attribute(string attname)
{
	remove_attribute(attname, true, Tango::Util::instance()->_UseDb);
	map<string,Tango::DevDouble>::iterator ite;
    if ((ite=MassScalarAttrib_data.find(attname))!=MassScalarAttrib_data.end())
    {
    	/*----- PROTECTED REGION ID(MKS_MicrovisionIP_RGA::remove_MassScalarAttrib_dynamic_attribute) ENABLED START -----*/
    	
    	/*----- PROTECTED REGION END -----*/	//	MKS_MicrovisionIP_RGA::remove_MassScalarAttrib_dynamic_attribute
		MassScalarAttrib_data.erase(ite);
	}
}


//============================================================
//	Tool methods to get pointer on attribute data buffer 
//============================================================
//--------------------------------------------------------
/**
 *	Return a pointer on MassScalarAttrib data.
 *
 *  parameter attname: the specified attribute name.
 */
//--------------------------------------------------------
Tango::DevDouble *MKS_MicrovisionIP_RGA::get_MassScalarAttrib_data_ptr(string &name)
{
	map<string,Tango::DevDouble>::iterator ite;
    if ((ite=MassScalarAttrib_data.find(name))==MassScalarAttrib_data.end())
    {
		TangoSys_OMemStream	tms;
		tms << "Dynamic attribute " << name << " has not been created";
		Tango::Except::throw_exception(
					(const char *)"ATTRIBUTE_NOT_FOUND",
					tms.str().c_str(),
					(const char *)"MKS_MicrovisionIP_RGA::get_MassScalarAttrib_data_ptr()");
    }
	return  &(ite->second);
}


//=============================================================
//	Add/Remove dynamic command methods
//=============================================================


} //	namespace
